

INSERT INTO AUTHOR VALUES ('1', 'PHAM', 'PHAM@GMAIL.COM', 'TEST', 'PICTURE')
INSERT INTO AUTHOR VALUES ('2', 'DUC', 'PHAM@GMAIL.COM', 'TEST', 'AVATAR')
INSERT INTO AUTHOR VALUES ('3', 'DAT', 'PHAM@GMAIL.COM', 'TEST', 'AVA')

INSERT INTO BLOG VALUES ('4', 'CSS', 'LEARN CSS', 'CSS', 'PIC', 'ART',TO_DATE('2021/1/03', 'YYYY/MM/DD'),1)
INSERT INTO BLOG VALUES ('5', 'HTML', 'LEARN HTML', 'HTML', 'PICTURE','BLOG',TO_DATE('2021/2/03', 'YYYY/MM/DD'),2)
INSERT INTO BLOG VALUES ('6', 'JS', 'LEARN JS', 'JS', 'TEST', 'ART',TO_DATE('2021/3/03', 'YYYY/MM/DD'),3)

INSERT INTO CONTACT VALUES ('7', 'CONTACT_1', 'TO', 'FROM','QUESTION', 1)


